name: 构建和推送 Docker 镜像

on:
  push:
    branches: [ "dev", "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "dev", "main" ]
  workflow_dispatch:

env:
  # 私有镜像仓库地址，macroverse-cn-beijing.cr.volces.com
  PRIVATE_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  # 镜像名称（不包含registry地址）
  IMAGE_NAME: macroverse/deepddg

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: 检出代码
      uses: actions/checkout@v5

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
          driver: docker

    - name: 从tos拷贝数据
      run: |
        cp -r /dp-macroverse/lyh/deepddg/* .

    - name: 调试 - 显示环境变量
      run: |
        echo runner.name: ${{ runner.name }}
        echo "PRIVATE_REGISTRY: ${{ env.PRIVATE_REGISTRY }}"
        echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
        echo "完整镜像地址: ${{ env.PRIVATE_REGISTRY }}/${{ env.IMAGE_NAME }}"

    - name: 登录到私有镜像仓库
      uses: docker/login-action@v3
      with:
        registry: ${{ env.PRIVATE_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 提取 Docker 元数据
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.PRIVATE_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}
            

    # - name: 构建并推送 Docker 镜像
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    #     no-cache: true
    #     # build-args: |
    #     #   BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

    - name: 清理docker images
      run: |
        docker rmi $(docker images -q)
        docker system prune -f
